catalog:
  services:
    - id: 5085f1cb-e093-4630-8795-843b76018eb8
      name: postgresql-db
      description: Manage PostgreSQL databases.
      bindable: true
      tags:
        - postgresql
        - database
      metadata:
        displayName: PostgreSQL
        imagUerl: https://raw.githubusercontent.com/cskksc/cf-postgresql-broker/master/postgresql_icon.png
        longDescription: The service allows a user to create and manage PostgreSQL databases.
        providerDisplayName: Chaitanya
        documentationUrl: https://github.com/cskksc/cf-postgresql-broker
        supportUrl: https://github.com/cskksc/cf-postgresql-broker
      plans:
        - id: c05855e7-a55d-4ba1-b462-7579df7514f4
          name: development
          description: Free trial
          metadata:
            bullets:
              - Shared PostgreSQL server
            costs:
              - amount:
                  usd: 0.0
                unit: MONTHLY
            displayName: Development
basic_auth:
  username: admin
  password: admin

postgresql:
  host: localhost
  username: admin
  password: admin
  port: 5432